version: "3"
services:
  react-simple-cloudword:
    # stdin_open: true
    # tty: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /app
        # excludes:
        #   - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./env